### ISSUE TITLE
Cant edit statistic TIME_PLAYED

### ISSUE THREAD

**Issue by 0ofland** [datatags/StatisticEditor#1]
Cant edit the statistic `TIME_PLAYED` 
The listed wiki says `minecraft:play_time ` which also doesn't work as well as `play_time`.
The plugin just spits out "Not a valid stat:".
Did I use the wrong statistic, and if yes, what is the right one?

**Comment by datatags** [comment]
Hello,
The Spigot name for that statistic is PLAY_ONE_MINUTE although its value is in ticks. See Spigot statistic list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Statistic.html
This is because that's what the statistic was named in 1.8 and Spigot has not updated their names in its list to preserve backwards compatibility.

There is a config option to use vanilla stat names but it's disabled by default because it's a bit hacky.

Alternatively, in the GitHub wiki here there is a conversion table from vanilla to Spigot and back.

Thanks for using StatisticEditor!

**Comment by 0ofland** [comment]
That worked, thanks you very much!
